{"uuid": "a1757900-2270-4d97-b744-3eb0ff5bdc34", "children": ["4dec884b-65b1-414d-afe7-73abe0fb9098"], "afters": [{"name": "BuiltIn.Run Keyword If Test Failed", "status": "failed", "statusDetails": {"message": "MaxRetryError: HTTPConnectionPool(host='localhost', port=51419): Max retries exceeded with url: /session/e646614c33c8a2f288bf15adb4bc3e16/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002489B792BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"}, "steps": [{"name": "SeleniumLibrary.Capture Page Screenshot", "status": "failed", "statusDetails": {"message": "MaxRetryError: HTTPConnectionPool(host='localhost', port=51419): Max retries exceeded with url: /session/e646614c33c8a2f288bf15adb4bc3e16/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002489B792BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"}, "attachments": [{"name": "Keyword Log", "source": "1c28da4d-8a1c-42a9-bde4-b478c2cfc18b-attachment.html", "type": "text/html"}], "start": 1755158503562, "stop": 1755158536347}], "stop": 1755158536348}]}